export const workspaceStyles = {
  sidebar: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
  card: {
    backgroundColor: '#15181A',
    border: '1px solid #202427',
    borderRadius: '8px',
    padding: '1.25rem',
  },
  cardTitle: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#FFFFFF',
    margin: '0 0 1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  roleRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1C1F22',
    padding: '0.75rem',
    borderRadius: '6px',
    border: '1px solid #2A2F34',
    marginBottom: '1rem',
  },
  roleLabel: {
    fontSize: '0.8rem',
    color: '#9CA3AF',
  },
  roleVal: {
    fontSize: '0.85rem',
    fontWeight: '700',
    color: '#D8C7AF',
  },
  actionsBox: {
    backgroundColor: '#111314',
    padding: '0.75rem',
    borderRadius: '6px',
    border: '1px solid #1D2022',
  },
  subLabel: {
    fontSize: '0.75rem',
    color: '#9CA3AF',
    display: 'block',
    marginBottom: '0.5rem',
  },
  noActionsText: {
    fontSize: '0.8rem',
    color: '#9CA3AF',
    margin: 0,
    fontStyle: 'italic' as const,
  },
  actionsList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.4rem',
  },
  actionItem: {
    fontSize: '0.8rem',
    color: '#34D399',
  },
  emptyText: {
    fontSize: '0.8rem',
    color: '#9CA3AF',
    fontStyle: 'italic' as const,
    margin: '0 0 1rem',
  },
  bindingsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.6rem',
    marginBottom: '1rem',
  },
  bindingItem: {
    backgroundColor: '#1C1F22',
    padding: '0.6rem',
    borderRadius: '6px',
    border: '1px solid #252A2D',
  },
  bindingHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bindingType: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#D8C7AF',
  },
  bindingIdCode: {
    fontSize: '0.75rem',
    color: '#FFFFFF',
    backgroundColor: '#111314',
    padding: '0.1rem 0.3rem',
    borderRadius: '3px',
  },
  sideForm: {
    marginTop: '1rem',
    borderTop: '1px solid #202427',
    paddingTop: '1rem',
  },
  formTitle: {
    fontSize: '0.8rem',
    color: '#FFFFFF',
    margin: '0 0 0.6rem',
  },
  formGroup: {
    marginBottom: '0.5rem',
  },
  formGroupRow: {
    display: 'flex',
    gap: '0.5rem',
  },
  selectInput: {
    width: '100%',
    backgroundColor: '#1E2225',
    border: '1px solid #2E3338',
    color: '#FFFFFF',
    padding: '0.4rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    outline: 'none',
  },
  textInput: {
    flex: 1,
    backgroundColor: '#1E2225',
    border: '1px solid #2E3338',
    color: '#FFFFFF',
    padding: '0.4rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    outline: 'none',
  },
  addBtn: {
    backgroundColor: '#D8C7AF',
    color: '#0F1112',
    border: 'none',
    padding: '0 0.6rem',
    borderRadius: '4px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moduleTitle: {
    fontSize: '1.1rem',
    color: '#FFFFFF',
    margin: '0 0 1.25rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  readOnlyLabel: {
    fontSize: '0.7rem',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#EF4444',
    padding: '0.15rem 0.4rem',
    borderRadius: '3px',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
  },
  chatThread: {
    height: '240px',
    backgroundColor: '#111314',
    borderRadius: '6px',
    border: '1px solid #1D2022',
    padding: '1rem',
    overflowY: 'auto' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
    marginBottom: '1rem',
  },
  chatMsg: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.2rem',
  },
  chatSender: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#D8C7AF',
  },
  chatBody: {
    fontSize: '0.85rem',
    color: '#E3E4E6',
    margin: 0,
  },
  chatInputRow: {
    display: 'flex',
    gap: '0.75rem',
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#1E2225',
    border: '1px solid #2E3338',
    color: '#FFFFFF',
    padding: '0.6rem 0.8rem',
    borderRadius: '6px',
    fontSize: '0.85rem',
    outline: 'none',
  },
  chatSendBtn: {
    backgroundColor: '#D8C7AF',
    color: '#0F1112',
    border: 'none',
    padding: '0 1.25rem',
    borderRadius: '6px',
    fontSize: '0.85rem',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
  },
  lockedBanner: {
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    border: '1px solid rgba(239, 68, 68, 0.1)',
    borderRadius: '6px',
    padding: '0.75rem',
    textAlign: 'center' as const,
    color: '#EF4444',
    fontSize: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  calendarMock: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1rem',
  },
  calendarDayActive: {
    backgroundColor: 'rgba(216, 199, 175, 0.05)',
    border: '1px solid #D8C7AF',
    borderRadius: '6px',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  calendarDay: {
    backgroundColor: '#1A1D20',
    border: '1px solid #22272A',
    borderRadius: '6px',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  dayNum: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  dayLabel: {
    fontSize: '0.75rem',
    color: '#9CA3AF',
    marginBottom: '0.5rem',
  },
  eventText: {
    fontSize: '0.8rem',
    color: '#D8C7AF',
    margin: 0,
  },
  eventTextEmpty: {
    fontSize: '0.8rem',
    color: '#4B5563',
    margin: 0,
  },
  voteMock: {
    backgroundColor: '#1A1D20',
    padding: '1rem',
    borderRadius: '6px',
    border: '1px solid #22272A',
  },
  voteQuestion: {
    fontSize: '0.9rem',
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: '1rem',
  },
  voteOptions: {
    display: 'flex',
    gap: '1rem',
  },
  voteBtn: {
    flex: 1,
    backgroundColor: '#252A2D',
    border: '1px solid #31373B',
    color: '#9CA3AF',
    padding: '0.5rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    cursor: 'not-allowed',
  },
  budgetMock: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  budgetItem: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.85rem',
    color: '#9CA3AF',
    borderBottom: '1px dashed #202427',
    paddingBottom: '0.4rem',
  },
  budgetVal: {
    color: '#FFFFFF',
  },
  budgetTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.95rem',
    fontWeight: '700',
    color: '#D8C7AF',
    marginTop: '0.5rem',
  },
};
