'use client';

import { useEffect, useState, createContext, useContext } from 'react';
import { loadSiteSettings, SiteSettings } from '@/lib/db';
import Script from 'next/script';
import { usePathname } from 'next/navigation';

interface SiteSettingsContextType {
  settings: SiteSettings | null;
  isLoading: boolean;
  refreshSettings: () => Promise<void>;
}

const SiteSettingsContext = createContext<SiteSettingsContextType>({
  settings: null,
  isLoading: true,
  refreshSettings: async () => {},
});

export const useSiteSettings = () => useContext(SiteSettingsContext);

export function SiteSettingsProvider({ children }: { children: React.ReactNode }) {
  const [settings, setSettings] = useState<SiteSettings | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const pathname = usePathname();

  const refreshSettings = async () => {
    setIsLoading(true);
    const data = await loadSiteSettings();
    if (data) {
      setSettings(data);
    }
    setIsLoading(false);
  };

  // Don't inject analytics or custom code on admin pages
  const isAdminPage = pathname?.startsWith('/admin');

  useEffect(() => {
    async function initSettings() {
      const data = await loadSiteSettings();
      if (data) {
        setSettings(data);
        
        const faviconUrl = data.brand?.faviconUrl || data.general?.faviconUrl;
        if (faviconUrl) {
          let favicon = document.querySelector('link[rel="icon"]');
          if (!favicon) {
            favicon = document.createElement('link');
            favicon.setAttribute('rel', 'icon');
            document.head.appendChild(favicon);
          }
          favicon.setAttribute('href', faviconUrl);
        }

        // Update document title and meta description if we aren't in the builder
        if (!isAdminPage) {
          if (data.seo?.defaultTitle && document.title === 'Create Next App') {
            document.title = data.seo.defaultTitle;
          }
          
          if (data.seo?.defaultDescription) {
            let metaDescription = document.querySelector('meta[name="description"]');
            if (!metaDescription) {
              metaDescription = document.createElement('meta');
              metaDescription.setAttribute('name', 'description');
              document.head.appendChild(metaDescription);
            }
            if (metaDescription.getAttribute('content') === 'Generated by create next app') {
              metaDescription.setAttribute('content', data.seo.defaultDescription);
            }
          }

          if (data.injection?.headCode) {
            // Only inject once to prevent duplicates on re-renders
            if (!document.getElementById('custom-head-code')) {
              const div = document.createElement('div');
              div.id = 'custom-head-code';
              div.style.display = 'none';
              div.innerHTML = data.injection.headCode;
              
              // We append the elements from the div into the head
              Array.from(div.children).forEach(child => {
                if (child.tagName === 'SCRIPT') {
                  const newScript = document.createElement('script');
                  Array.from(child.attributes).forEach(attr => newScript.setAttribute(attr.name, attr.value));
                  newScript.text = child.textContent || '';
                  document.head.appendChild(newScript);
                } else {
                  document.head.appendChild(child.cloneNode(true));
                }
              });
              
              // Add the tracking div to the body so we don't inject again
              document.body.appendChild(div);
            }
          }
        }
      }
      setIsLoading(false);
    }
    initSettings();
  }, [isAdminPage]);

  return (
    <SiteSettingsContext.Provider value={{ settings, isLoading, refreshSettings }}>
      {!isAdminPage && settings?.injection?.googleAnalyticsId && (
        <>
          {settings.injection.googleAnalyticsId.startsWith('GTM-') ? (
            <Script id="google-tag-manager" strategy="afterInteractive">
              {`
                (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','${settings.injection.googleAnalyticsId}');
              `}
            </Script>
          ) : (
            <>
              <Script 
                src={`https://www.googletagmanager.com/gtag/js?id=${settings.injection.googleAnalyticsId}`}
                strategy="afterInteractive"
              />
              <Script id="google-analytics" strategy="afterInteractive">
                {`
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){window.dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '${settings.injection.googleAnalyticsId}');
                `}
              </Script>
            </>
          )}
        </>
      )}

      {!isAdminPage && settings?.injection?.googleAnalyticsId && settings.injection.googleAnalyticsId.startsWith('GTM-') && (
        <Script id="gtm-purchase" strategy="afterInteractive">
          {`
            (function() {
              const params = new URLSearchParams(window.location.search);
              if (params.get('status') === 'success') {
                const bookingId = params.get('bookingId') || params.get('id');
                if (bookingId) {
                  const trackedKey = 'gtm_tracked_purchase_' + bookingId;
                  if (!localStorage.getItem(trackedKey)) {
                    const storedValue = localStorage.getItem('checkout_value_' + bookingId);
                    const storedItemName = localStorage.getItem('checkout_item_name_' + bookingId);
                    
                    const bookingValue = storedValue ? parseFloat(storedValue) : 0;
                    const itemName = storedItemName || 'Yacht Charter';
                    
                    window.dataLayer = window.dataLayer || [];
                    window.dataLayer.push({
                      event: 'purchase',
                      ecommerce: {
                        transaction_id: bookingId,
                        value: bookingValue,
                        currency: 'USD',
                        items: [{
                          item_id: bookingId,
                          item_name: itemName,
                          price: bookingValue,
                          quantity: 1
                        }]
                      }
                    });
                    localStorage.setItem(trackedKey, 'true');
                  }
                }
              }
            })();
          `}
        </Script>
      )}

      {!isAdminPage && settings?.injection?.metaPixelId && (
        <>
          <Script id="meta-pixel" strategy="afterInteractive">
            {`
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '${settings.injection.metaPixelId}');
              fbq('set', 'autoConfig', false, '${settings.injection.metaPixelId}');
              fbq('track', 'PageView');
            `}
          </Script>
          <Script id="meta-pixel-purchase" strategy="afterInteractive">
            {`
              (function() {
                const params = new URLSearchParams(window.location.search);
                if (params.get('status') === 'success') {
                  const bookingId = params.get('bookingId') || params.get('id');
                  if (bookingId) {
                    const trackedKey = 'fb_tracked_purchase_' + bookingId;
                    if (!localStorage.getItem(trackedKey)) {
                      window.fbq('track', 'Purchase', {
                        content_type: 'product',
                        contents: [{ id: bookingId }],
                        currency: 'USD'
                      }, { eventID: bookingId });
                      localStorage.setItem(trackedKey, 'true');
                    }
                  }
                }
              })();
            `}
          </Script>
          <noscript>
            <img height="1" width="1" style={{ display: 'none' }} 
              src={`https://www.facebook.com/tr?id=${settings.injection.metaPixelId}&ev=PageView&noscript=1`} />
          </noscript>
        </>
      )}


      {children}

      {!isAdminPage && settings?.injection?.bodyCode && (
        <div 
          dangerouslySetInnerHTML={{ __html: settings.injection.bodyCode }} 
          style={{ display: 'none' }}
        />
      )}
    </SiteSettingsContext.Provider>
  );
}
